apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: demoservice.manual-ab
spec:
  hosts:
  - "demoservice"
  http:
  - route:
    - destination:
        host: demoservice
        subset: v1
        port:
          number: 8080
      weight: 10
    - destination:
        host: demoservice
        subset: v2
        port:
          number: 8080
      weight: 90
