apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: demoservice
spec:
  hosts:
  - "demo.local"
  gateways:
  - demoservice-gateway
  http:  
   - route:
     - destination:
        host: demoservice
        port:
          number: 8080


