
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: demoservice-destination 
spec:
  host: demoservice
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: demoservice
spec:
  hosts:
  - "demo.local"
  gateways:
  - demoservice-gateway
  http:         
#  - match:  
#    - uri:
#        regex: '/(.*)' 
    route:
    - destination: 
        host: demoservice
        subset: v1
        port:
          number: 8080
      weight: 50
    - destination: 
        host: demoservice
        subset: v2
        port:
          number: 8080
      weight: 50
