apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: configservice
spec:
  hosts:
  - "*" 
  gateways:
  - demoservice-gateway
  selector:
      matchLabels:
        name: configservice
  http:  
   - route:
     - destination:
        host: config-frontend
        port:
          number: 8080
 